### ISSUE TITLE
Loading Circle

### ISSUE THREAD

**Issue by Chuck-Gibson** [Chuck-Gibson/reddit-app#11]
![loadingCircle](https://user-images.githubusercontent.com/90487306/191155181-9f4cec79-aea4-4887-8618-bc27c0ca6f0d.png)

built a quick loading circle but wasn't sure if you had an idea in mind so figured id check for feedback first

**Comment by hn275** [comment]
looks great as it is! but if you round out the edge, it would go better with rounded edge them we got going on.

**Comment by Chuck-Gibson** [comment]
because it is built with borders in Css, i cannot guarantee i can do that but i will try
