### ISSUE TITLE
Nav bar z-index

### ISSUE THREAD

**Issue by hn275** [Chuck-Gibson/reddit-app#8]
I can fix this myself, but I'm not too sure how you would go about it, so it's just easier for me to create an issue.

I have not set any `z-index` for the _**individual post component**_, but nav bar is hiding behind the posts as I scroll, this maybe due to the fact that the nav bar is one of the first components that is rendered to the DOM.

![reddit-client-navbar-issue](https://user-images.githubusercontent.com/97143596/190936855-e63cfbd3-db25-4de7-b6e6-f693af21ee07.png)

## One way to go about fixing this

In `src/components/header/header.css`

```css
.Header {
  /* existing rules */
  z-index: 999;
}
```

**Comment by Chuck-Gibson** [comment]
Fixed in the next commit
